Unica/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Unica.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Unica.Controllers
{
    public class ClienteController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }


    }
}

Unica/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Unica.Models;
using Unica.Data;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Unica.Controllers
{
    public class ContratoController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            using (var data = new ContratoData())
                return View(data.Read());
        }

        [HttpGet]
        public IActionResult Create()
        {
            List<Veiculo> veiculos;
            using (var data = new VeiculoData())
            {
                veiculos = data.Read();
            }

            List<Cliente> clientes;
            using (var data = new ClienteData())
            {
                clientes = data.Read();
            }

            ViewBag.Veiculos = veiculos.FindAll(value => value.Status == 1);
            ViewBag.Clientes = clientes;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contrato Contrato)
        {
            Contrato.Status = 1;
            if (!ModelState.IsValid)
            {
                return View(Contrato);
            }

            using (var data = new ContratoData())
                data.Create(Contrato);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            List<Veiculo> veiculos;
            using (var data = new VeiculoData())
            {
                veiculos = data.Read();
            }

            List<Cliente> clientes;
            using (var data = new ClienteData())
            {
                clientes = data.Read();
            }

            ViewBag.Veiculos = veiculos;
            ViewBag.Clientes = clientes;
            using (var data = new ContratoData())
                return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(Contrato contrato)
        {
            if (!ModelState.IsValid)
            {
                return View(contrato);
            }

            using (var data = new ContratoData())
                data.Update(contrato);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            using (var data = new ContratoData())
                data.Delete(id);

            return RedirectToAction("Index");
        }

        public IActionResult Finalizar(int id)
        {
            using (var data = new ContratoData())
                data.Finalizar(id);

            return RedirectToAction("Index");
        }

    }
}

Unica/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Unica.Models;
using Unica.Data;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Unica.Controllers
{
    public class VeiculoController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            using (var data = new VeiculoData())
                return View(data.Read());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Veiculo veiculo)
        {
            veiculo.Status = 1;
            if (!ModelState.IsValid)
            {
                return View(veiculo);
            }

            using (var data = new VeiculoData())
                data.Create(veiculo);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            using (var data = new VeiculoData())
                return View(data.ReadById(id));
        }

        [HttpPost]
        public IActionResult Update(Veiculo veiculo)
        {
            if (!ModelState.IsValid)
            {
                return View(veiculo);
            }

            using (var data = new VeiculoData())
                data.Update(veiculo);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            using (var data = new VeiculoData())
                data.Delete(id);

            return RedirectToAction("Index");
        }

    }
}

Unica/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@using System.Text.Json
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    @{
        string json = HttpContextAccessor.HttpContext.Session.GetString("user");

        if (json != null)
        {
            Funcionario user = JsonSerializer.Deserialize<Funcionario>(json);

            if (user != null)
            {
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Unica</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Veiculo"
                                    asp-action="Index">Veiculos</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Cliente"
                                    asp-action="Index">Clientes</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Contrato"
                                    asp-action="Index">Contrato</a>
                                    </li>
                                </ul>
                                <ul style="position: absolute; right: 5;" class="navbar-nav ml-auto">
                                    <li class="nav-item">
                                        <a href="/funcionario/update/@user.Id" class="nav-link text-dark">Bem vindo @user.Nome</a>
                                    </li>
                                    <li class="nav-item">
                                        <form asp-controller="Funcionario" asp-action="Logout" method="post"><button
                                        class="nav-link" style="border: 0; background-color: white ;color:red">Sair</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </header>
            }
        }
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Unica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>